os:
  editPreset: "nvim"

keybinding:
  universal:
    return: '<c-\>'

gui:
  theme:
    selecteLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
git: 
  autoFetch: false
  autoRefresh: false

