os:
  editPreset: "nvim"

gui:
  theme:
    selecteLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
git:
  autoFetch: false
  autoRefresh: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never
