require("user.options")
require("plugins")
require("user.keymaps")
require("user.lspconfigs")
require("user.bufferline")
require("user.telescope")
require("user.lualine")
require("user.nvim-tree")
require("user.treesitter")
--require("user.null_ls")

vim.cmd([[colorscheme tokyonight]])
