require("user.options")
require("plugins")
require("user.keymaps")
require("user.lspconfigs")
require("user.bufferline")
require("user.telescope")
require("user.lualine")
require("user.nvim-tree")
require("user.treesitter")

--vim.cmd([[colorscheme tokyonight]])
vim.cmd([[colorscheme catppuccin]])
