abbr fishconfig "nvim ~/.zshrc"
abbr localconfig "nvim ~/.local-path-vars"
abbr lsplog "tail -f ~/.local/state/nvim/lsp.log"
abbr cdga "cd ~/gitprojects/arbol/"
abbr cdlp "cd ~/gitprojects/obsidian-plugins/obsidian-clipper-projects"
abbr cdt "cd ~/gitprojects/dotfiles"
abbr gitlog "git log --graph --pretty=format:'%Cred%h%Creset %C(bold blue)%an%C(reset) - %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
abbr ls "lsd"
